In [1]:
import os
import cv2

import numpy as np
import tensorflow as tf

from utils import train_val_generator

Using TensorFlow backend.


In [2]:
physical_devices = tf.config.list_physical_devices('GPU')
try:
  tf.config.experimental.set_memory_growth(physical_devices[0], True)
except:
  pass

In [3]:
train_path = './train'
test_path ='./test'

train_gen, val_gen = train_val_generator(16,train_path,test_path)

Found 636 images belonging to 2 classes.
Found 104 images belonging to 2 classes.


In [4]:
train_gen.class_indices

{'Clean': 0, 'Defected': 1}

In [5]:
model = tf.keras.models.load_model("vanilla_final.h5")

In [6]:
defected_image_dir = 'train/Defected'
images = os.listdir(defected_image_dir)

In [7]:
for i in images[:10]:
    img = np.reshape(np.array(cv2.resize(cv2.imread(defected_image_dir + '/' + i), (64,64))), (1,64,64,3))
    print(model.predict(img))

[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
